version: "3.9"

name: kanban

services:
  mysql:
    container_name: kanban-mysql
    image: mysql:8.0.32-debian
    environment:
      MYSQL_DATABASE: "kanban"
      MYSQL_ROOT_PASSWORD: "toor"
    ports:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"
    networks:
      app:
        ipv4_address: 10.0.0.3
    tty: true

  next:
    container_name: kanban-next
    image: kanban/next-prod
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      app:
        ipv4_address: 10.0.0.4
    tty: true

  nginx:
    container_name: kanban-nginx
    image: nginx:1.23.4-alpine
    volumes:
      - "./nginx/nginx.prod.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - next
    networks:
      app:
        ipv4_address: 10.0.0.2
    tty: true

volumes:
  mysql:
    driver: local

networks:
  app:
    name: kanban_app
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/29
          gateway: 10.0.0.1
