version: "3.9"

name: kanban

services:
  mysql:
    container_name: kanban-mysql
    image: mysql:8.0.32-debian
    environment:
      MYSQL_DATABASE: kanban
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"
    networks:
      - app

  next:
    container_name: kanban-next
    image: kanban/next-prod
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - app

volumes:
  mysql:
    driver: local

networks:
  app:
    name: kanban_app
    driver: bridge
