version: "3.9"

name: kanban

services:
  mysql:
    container_name: kanban-mysql
    image: mysql:8.0.32-debian
    environment:
      MYSQL_DATABASE: "kanban"
      MYSQL_ROOT_PASSWORD: "toor"
    ports:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"
    networks:
      app:
        ipv4_address: 10.0.0.3
    tty: true

  next:
    container_name: kanban-next
    image: kanban/next-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    entrypoint: ["npm", "run", "dev"]
    environment:
      NODE_ENV: "development"
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    depends_on:
      - mysql
    networks:
      app:
        ipv4_address: 10.0.0.4
    tty: true

  studio:
    container_name: kanban-studio
    image: kanban/next-dev
    entrypoint: ["npx", "prisma", "studio"]
    environment:
      NODE_ENV: "development"
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - next
    networks:
      app:
        ipv4_address: 10.0.0.5
    tty: true

  codegen:
    container_name: kanban-codegen
    image: kanban/next-dev
    entrypoint: ["npm", "run", "codegen", "--", "--watch"]
    environment:
      NODE_ENV: "development"
    volumes:
      - ".:/app"
    depends_on:
      - next

  nginx:
    container_name: kanban-nginx
    image: nginx:1.23.4-alpine
    entrypoint: ["nginx", "-g", "daemon off;", "-q"]
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - next
    networks:
      app:
        ipv4_address: 10.0.0.2
    tty: true

volumes:
  mysql:
    driver: local

networks:
  app:
    name: kanban_app
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/29
          gateway: 10.0.0.1
