networks:
  proxy:
    external: true

services:
  traefik:
    image: traefik:v3.0.2
    command:
      - --providers.docker=true
      - --providers.docker.network=proxy
      - --providers.docker.exposedbydefault=false
      - --api.dashboard=true
      - --entrypoints.web.address=:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.kanban.$CNAME`)
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.service=api@internal
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
